#if !canImport(ObjectiveC)
import XCTest

extension ColorizerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ColorizerTests = [
        ("testBackgroundExtension", testBackgroundExtension),
        ("testForegroundExtension", testForegroundExtension),
        ("testMixingStylesExtension", testMixingStylesExtension),
        ("testStyleExtension", testStyleExtension),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ColorizerTests.__allTests__ColorizerTests),
    ]
}
#endif
